<a href="https://colab.research.google.com/github/Nelrau/numpy/blob/main/numpy_10_exercicios_parte_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Exercício

Você é um gerente de vendas e tem os dados de vendas de três produtos diferentes (Produto A, Produto B, Produto C) para os últimos 5 dias em um array 2D NumPy. Cada linha do array representa um produto e cada coluna representa um dia. Seu trabalho é calcular as vendas totais para cada produto e para cada dia.

Use o seguinte array para sua análise:

```python
vendas = np.array([[50, 60, 70, 65, 80],
                   [85, 90, 78, 92, 88],
                   [72, 75, 68, 77, 76]])
```

**Solução:**


In [19]:
from re import A
import numpy as np

vendas = np.array([[50, 60, 70, 65, 80],
                   [85, 90, 78, 92, 88],
                   [72, 75, 68, 77, 76]])
#produto
print(vendas.sum(axis=1))
print(np.sum(vendas,axis=1))
print('\n__x__\n')
#dia
print(vendas.sum(axis=0))
print(np.sum(vendas,axis=0))

[325 433 368]
[325 433 368]

__x__

[207 225 216 234 244]
[207 225 216 234 244]


In [25]:
v_produto = vendas.sum(axis=1)
print(f'venda de produto A - {v_produto[0]}')

venda de produto A - 325


In [29]:
v_dias = vendas.sum(axis=0)
for i in range(0,5):
  print(f'venda do dia {i+1} - {v_dias[i]}')


venda do dia 1 - 207
venda do dia 2 - 225
venda do dia 3 - 216
venda do dia 4 - 234
venda do dia 5 - 244
